_BASE_: ../maskformer2_R50_bs16_50ep.yaml

MODEL:
  META_ARCHITECTURE: "MaskFormerTTT"
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    IN_CHANS: 4
  WEIGHTS: "swin_small_patch4_window7_224.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]

SOLVER:
  IMS_PER_BATCH: 1
  ACCUM_ITER: 4
  BASE_LR: 0.0001
  MAX_ITER: 4000000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True

TEST:
  EVAL_PERIOD: 4000000

TTT:
  IN_DIR: ./
  OUT_DIR: ./
  EXP_DIR: ./
  ST_ITERS: 1
  HP: -1
  RESTART_OPTIMIZER: True